name: Firebase Deploy
run-name: Deploy middleware to Firebase
on:
  push:
    branches:
      - main
      - test
jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Biome Lint Check
        run: |
          cd ./functions
          bun add @biomejs/biome
          bunx --bun @biomejs/biome lint ./src
  deploy-prod-backend:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Build and create env file
        run: | 
          bun i --allow-scripts
          cd ./functions 
          bun i --allow-scripts
          bun run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions -P ddmerch-middlewear
        env:
          GCP_SA_KEY: ${{ secrets.PROD_SERVICE_ACCOUNT_JSON }}
          PROJECT_ID: dd-middleware
  
  deploy-test-backend:
    needs: lint-check
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Build and create env file
        run: | 
          bun i --allow-scripts
          cd ./functions 
          bun i --allow-scripts
          bun run build
      - name: Install Firebase CLI
        run: bun add -g firebase-tools
      - name: Deploy to Firebase
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=gcp_key.json
          echo '${{ secrets.TEST_SERVICE_ACCOUNT_JSON }}' > gcp_key.json
          firebase deploy --only functions -P dd-middleware-test