name: Firebase Deploy
run-name: Deploy middleware to Firebase
on:
  push:
    branches:
      - main
      - test
jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun add @biomejs/biome
      - run: bunx --bun @biomejs/biome lint ./functions/src ./modules
  # firebase-deploy-main:
  #   if: github.ref == 'refs/heads/main' # Only runs on the main branch
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Linting code"
  #     - run: bunx --bun @biomejs/biome lint ./functions/src ./modules
  
  firebase-deploy-test:
    needs: lint-check
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun i --allow-scripts && cd ./functions && bun i --allow-scripts 
      - run: cd ./functions && bun run build
      - run: bunx firebase deploy --only functions --project dd-middleware-test --token "${{ secrets.FIREBASE_TOKEN }}"